{ config, pkgs, ... }:

{
  imports = [
    # Include hardware configuration (will be generated on the target system)
    # ./hardware-configuration.nix
    
    # Import our modules
    ./modules/utils.nix
    ./modules/imports.nix  # This will be generated by the install script
  ];
  
  # Basic system configuration
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  
  # Networking
  networking.networkmanager.enable = true;
  
  # Set your time zone
  time.timeZone = "Europe/Paris";
  
  # Internationalization
  i18n.defaultLocale = "en_US.UTF-8";
  
  # keyboard layout
  services.xserver = {
  layout = "fr";  // Change to your preferred layout (e.g., "fr", "de", etc.)
  xkbVariant = "";  // Use variants like "dvorak" or "colemak" if needed
  xkbOptions = "eurosign:e";  // Optional: additional XKB options
  };

  # Also add console keyboard layout
  console.keyMap = "fr";  // Change to match your keyboard layout

  # User configuration
  users.users.YOUR_USERNAME = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
    # Add a password hash or initialPassword if desired
  };
  
  # System-wide packages
  environment.systemPackages = with pkgs; [
    wget               # Network utility to retrieve files from the web
    neovim             # Highly configurable text editor
    git                # Distributed version control system
    curl               # Command line tool for transferring data with URLs
  ];
  
  # Nix settings
  nix = {
    settings = {
      experimental-features = [ "nix-command" "flakes" ];
      auto-optimise-store = true;
    };
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 30d";
    };
  };
  
  # Allow unfree packages
  nixpkgs.config.allowUnfree = true;
  
  # Enable sound with Pipewire
  sound.enable = true;
  hardware.pulseaudio.enable = false; # Disable PulseAudio
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true; # PulseAudio compatibility
    jack.enable = true;  # JACK compatibility
  };
  
  # This value determines the NixOS release to use
  system.stateVersion = "23.11"; # Set to your NixOS version
}